name: Release Automatizado

# Aciona o workflow sempre que houver um push para a branch principal (main)
on:
  push:
    branches:
      - main
  # Permite a execu\u00e7\u00e3o manual (opcional)
  workflow_dispatch:

# Define as permiss\u00f5es necess\u00e1rias para que o workflow possa criar tags e releases
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  # Job principal para criar o release
  release:
    name: Criar Novo Release
    runs-on: ubuntu-latest
    
    steps:
    
      # 1. Checkout do C\u00f3digo
      - name: Checkout do c\u00f3digo
        uses: actions/checkout@v4
        with:
          # Fetch all history and tags to allow semantic-release to calculate the version
          fetch-depth: 0
      
      # 2. Configura\u00e7\u00e3o do Ambiente Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Use a vers\u00e3o do Python que voc\u00ea usa no projeto

      # 3. Cache de Depend\u00eancias (Opcional, mas recomendado para velocidade)
      - name: Configurar Cache
        uses: actions/cache@v4
        with:
          path: ${{ env.PYTHON_ENV_PATH }}
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4. Instalar Semantic Release
      # Usaremos o pipx para garantir uma instala\u00e7\u00e3o isolada e correta.
      - name: Instalar python-semantic-release
        run: |
          python -m pip install --upgrade pip
          pip install pipx
          pipx install python-semantic-release

      # 5. Criar o Release
      - name: Executar o Release
        env:
          # TOKEN de seguran\u00e7a fornecido automaticamente pelo GitHub
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # O \u00fanico par\u00e2metro necess\u00e1rio \u00e9 --commit-version-number para atualizar o \u00e2__version__\u00e2 no seu __init__.py
          # Certifique-se de configurar corretamente o semantic-release no pyproject.toml para:
          # - Ler a vers\u00e3o de src/meu_pacote/__init__.py
          # - Fazer commit das altera\u00e7\u00f5es (ex: git tag, git commit)
          pipx run python-semantic-release publish -D commit_type="chore"
